export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CLEAR_ITEM_EDITNG = 'CLEAR_ITEM_EDITNG';
export const LOAD_DATA_WARE_HOUSES_REQUEST = 'LOAD_DATA_WARE_HOUSES_REQUEST';
export const LOAD_DATA_WARE_HOUSES_SUCCESS = 'LOAD_DATA_WARE_HOUSES_SUCCESS';
export const LOAD_DATA_WARE_HOUSES_FAIL = 'LOAD_DATA_WARE_HOUSES_FAIL';
export const ADD_WARE_HOUSE_REQUEST = 'ADD_WARE_HOUSE_REQUEST';
export const ADD_WARE_HOUSE_SUCCESS = 'ADD_WARE_HOUSE_SUCCESS';
export const ADD_WARE_HOUSE_FAIL = 'ADD_WARE_HOUSE_FAIL';
export const LOAD_DATA_WARE_HOUSE_REQUEST = 'LOAD_DATA_WARE_HOUSE_REQUEST';
export const LOAD_DATA_WARE_HOUSE_SUCCESS = 'LOAD_DATA_WARE_HOUSE_SUCCESS';
export const UPDATE_WARE_HOUSE_REQUEST = 'UPDATE_WARE_HOUSE_REQUEST';
export const UPDATE_WARE_HOUSE_SUCCESS = 'UPDATE_WARE_HOUSE_SUCCESS';
export const UPDATE_WARE_HOUSE_FAIL = 'UPDATE_WARE_HOUSE_FAIL';
export const DELETE_WARE_HOUSE_REQUEST = 'DELETE_WARE_HOUSE_REQUEST';
export const DELETE_WARE_HOUSE_SUCCESS = 'DELETE_WARE_HOUSE_SUCCESS';
export const LOAD_DATA_CITY = 'LOAD_DATA_CITY';
export const LOAD_DATA_DISTRICT = 'LOAD_DATA_DISTRICT';
export const LOAD_DATA_COMMUNE = 'LOAD_DATA_COMMUNE';
export const CLEAR_STORE_TEAM = 'CLEAR_STORE_TEAM';


export const TAGS = 'TAGS';
export const LOAD_DATA_TAGS_REQUEST = 'LOAD_DATA_TAGS_REQUEST';
export const LOAD_DATA_TAGS_SUCCESS = 'LOAD_DATA_TAGS_SUCCESS';
export const LOAD_DATA_TAGS_FAIL = 'LOAD_DATA_TAGS_FAIL';
export const LOAD_DATA_TAG_REQUEST = 'LOAD_DATA_TAG_REQUEST';
export const LOAD_DATA_TAG_SUCCESS = 'LOAD_DATA_TAG_SUCCESS';
export const UPDATE_TAG_REQUEST = 'UPDATE_TAG_REQUEST';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAIL = 'UPDATE_TAG_FAIL';
export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_FAIL = 'ADD_TAG_FAIL';
export const SUGGESTIONS_FETCH_TAG = 'SUGGESTIONS_FETCH_TAG';
export const GET_WAREHOUSE_TAGS = 'GET_WAREHOUSE_TAGS';

export const PAYMENTS = 'PAYMENTS';
export const LOAD_DATA_PAYMENTS_REQUEST = 'LOAD_DATA_PAYMENTS_REQUEST';
export const LOAD_DATA_PAYMENTS_SUCCESS = 'LOAD_DATA_PAYMENTS_SUCCESS';
export const LOAD_DATA_PAYMENTS_FAIL = 'LOAD_DATA_PAYMENTS_FAIL';
export const UPDATE_STATUS_PAYMENT_REQUEST = 'UPDATE_STATUS_PAYMENT_REQUEST';
export const UPDATE_STATUS_PAYMENT_SUCCESS = 'UPDATE_STATUS_PAYMENT_SUCCESS';
export const UPDATE_STATUS_PAYMENT_FAIL = 'UPDATE_STATUS_PAYMENT_FAIL';
export const LOAD_DATA_PAYMENT_REQUEST = 'LOAD_DATA_PAYMENT_REQUEST';
export const LOAD_DATA_PAYMENT_SUCCESS = 'LOAD_DATA_PAYMENT_SUCCESS';
export const LOAD_DATA_PAYMENT_FAIL = 'LOAD_DATA_PAYMENT_FAIL';

export const LOAD_DATA_DETAIL_TICKET = 'LOAD_DATA_DETAIL_TICKET';
export const LOAD_DATA_DETAIL_TICKET_REQUEST = 'LOAD_DATA_DETAIL_TICKET_REQUEST';
export const LOAD_DATA_DETAIL_TICKET_SUCCESS = 'LOAD_DATA_DETAIL_TICKET_SUCCESS';
export const LOAD_DATA_DETAIL_TICKET_FAIL = 'LOAD_DATA_DETAIL_TICKET_SUCCESS_FAIL';



export const VENUES = 'VENUES';
export const LOAD_DATA_VENUES_REQUEST = 'LOAD_DATA_VENUES_REQUEST';
export const LOAD_DATA_VENUES_SUCCESS = 'LOAD_DATA_VENUES_SUCCESS';
export const LOAD_DATA_VENUES_FAIL = 'LOAD_DATA_VENUES_FAIL';
export const LOAD_DATA_VENUE_REQUEST = 'LOAD_DATA_VENUE_REQUEST';
export const LOAD_DATA_VENUE_SUCCESS = 'LOAD_DATA_VENUE_SUCCESS';
export const UPDATE_VENUE_REQUEST = 'UPDATE_VENUE_REQUEST';
export const UPDATE_VENUE_SUCCESS = 'UPDATE_VENUE_SUCCESS';
export const UPDATE_VENUE_FAIL = 'UPDATE_VENUE_FAIL';
export const DELETE_VENUE_REQUEST = 'DELETE_VENUE_REQUEST';
export const DELETE_VENUE_SUCCESS = 'DELETE_VENUE_SUCCESS';
export const ADD_VENUE_REQUEST = 'ADD_VENUE_REQUEST';
export const ADD_VENUE_SUCCESS = 'ADD_VENUE_SUCCESS';
export const ADD_VENUE_FAIL = 'ADD_VENUE_FAIL';
export const SUGGESTIONS_FETCH_VENUE = 'SUGGESTIONS_FETCH_VENUE';
export const GET_WAREHOUSE_VENUES = 'GET_WAREHOUSE_VENUES';
export const URL_CROP_IMG_VENUE = 'URL_CROP_IMG_VENUE';

export const EVENTS = 'EVENTS';
export const LOAD_DATA_EVENTS_REQUEST = 'LOAD_DATA_EVENTS_REQUEST';
export const LOAD_DATA_EVENTS_SUCCESS = 'LOAD_DATA_EVENTS_SUCCESS';
export const LOAD_DATA_EVENTS_FAIL = 'LOAD_DATA_EVENTS_FAIL';
export const LOAD_DATA_EVENT_REQUEST = 'LOAD_DATA_EVENT_REQUEST';
export const LOAD_DATA_EVENT_SUCCESS = 'LOAD_DATA_EVENT_SUCCESS';
export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';
export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';
export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL';
export const SUGGESTIONS_FETCH_EVENT = 'SUGGESTIONS_FETCH_EVENT';
export const GET_WAREHOUSE_EVENTS = 'GET_WAREHOUSE_EVENTS';
export const URL_CROP_IMG_EVENT = 'URL_CROP_IMG_EVENT';


export const TEAMS = 'TEAMS';
export const LOAD_DATA_TEAMS_REQUEST = 'LOAD_DATA_TEAMS_REQUEST';
export const LOAD_DATA_TEAMS_SUCCESS = 'LOAD_DATA_TEAMS_SUCCESS';
export const LOAD_DATA_TEAMS_FAIL = 'LOAD_DATA_TEAMS_FAIL';
export const LOAD_DATA_TEAM_NEWS_REQUEST = 'LOAD_DATA_TEAM_NEWS_REQUEST';
export const LOAD_DATA_TEAM_NEWS_SUCCESS = 'LOAD_DATA_TEAM_NEWS_SUCCESS';
export const LOAD_DATA_TEAM_NEWS_FAIL = 'LOAD_DATA_TEAM_NEWS_FAIL';
export const LOAD_DATA_TEAM_REQUEST = 'LOAD_DATA_TEAM_REQUEST';
export const LOAD_DATA_TEAM_SUCCESS = 'LOAD_DATA_TEAM_SUCCESS';
export const UPDATE_TEAM_REQUEST = 'UPDATE_TEAM_REQUEST';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAIL = 'UPDATE_TEAM_FAIL';
export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL';
export const ADD_TEAM_REQUEST = 'ADD_TEAM_REQUEST';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL';
export const SUGGESTIONS_FETCH_TEAM = 'SUGGESTIONS_FETCH_TEAM';
export const GET_WAREHOUSE_TEAMS = 'GET_WAREHOUSE_TEAMS';
export const URL_CROP_IMG_TEAM = 'URL_CROP_IMG_TEAM';


export const REFUNDS = 'REFUNDS';
export const LOAD_DATA_REFUNDS_REQUEST = 'LOAD_DATA_REFUNDS_REQUEST';
export const LOAD_DATA_REFUNDS_SUCCESS = 'LOAD_DATA_REFUNDS_SUCCESS';
export const LOAD_DATA_REFUNDS_FAIL = 'LOAD_DATA_REFUNDS_FAIL';
export const LOAD_DATA_REFUND_REQUEST = 'LOAD_DATA_REFUND_REQUEST';
export const LOAD_DATA_REFUND_SUCCESS = 'LOAD_DATA_REFUND_SUCCESS';
export const UPDATE_REFUND_REQUEST = 'UPDATE_REFUND_REQUEST';
export const UPDATE_REFUND_SUCCESS = 'UPDATE_REFUND_SUCCESS';
export const UPDATE_REFUND_FAIL = 'UPDATE_REFUND_FAIL';
export const DELETE_REFUND_REQUEST = 'DELETE_REFUND_REQUEST';
export const DELETE_REFUND_SUCCESS = 'DELETE_REFUND_SUCCESS';
export const ADD_REFUND_REQUEST = 'ADD_REFUND_REQUEST';
export const ADD_REFUND_SUCCESS = 'ADD_REFUND_SUCCESS';
export const ADD_REFUND_FAIL = 'ADD_REFUND_FAIL';
export const SUGGESTIONS_FETCH_REFUND = 'SUGGESTIONS_FETCH_REFUND';
export const GET_WAREHOUSE_REFUNDS = 'GET_WAREHOUSE_REFUNDS';
export const CROP_IMG_REFUND = 'CROP_IMG_REFUND';
export const URL_CROP_IMG_REFUND = 'URL_CROP_IMG_REFUND';
export const CLEAR_STORE_REFUND = 'CLEAR_STORE_REFUND';


export const BANNERS = 'BANNERS';
export const LOAD_DATA_BANNERS_REQUEST = 'LOAD_DATA_BANNERS_REQUEST';
export const LOAD_DATA_BANNERS_SUCCESS = 'LOAD_DATA_BANNERS_SUCCESS';
export const LOAD_DATA_BANNERS_FAIL = 'LOAD_DATA_BANNERS_FAIL';
export const LOAD_DATA_BANNER_REQUEST = 'LOAD_DATA_BANNER_REQUEST';
export const LOAD_DATA_BANNER_SUCCESS = 'LOAD_DATA_BANNER_SUCCESS';
export const UPDATE_BANNER_REQUEST = 'UPDATE_BANNER_REQUEST';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_FAIL = 'UPDATE_BANNER_FAIL';
export const DELETE_BANNER_REQUEST = 'DELETE_BANNER_REQUEST';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';
export const ADD_BANNER_REQUEST = 'ADD_BANNER_REQUEST';
export const ADD_BANNER_SUCCESS = 'ADD_BANNER_SUCCESS';
export const ADD_BANNER_FAIL = 'ADD_BANNER_FAIL';
export const SUGGESTIONS_FETCH_BANNER = 'SUGGESTIONS_FETCH_BANNER';
export const GET_WAREHOUSE_BANNERS = 'GET_WAREHOUSE_BANNERS';
export const CROP_IMG_BANNER = 'CROP_IMG_BANNER';
export const URL_CROP_IMG_BANNER = 'URL_CROP_IMG_BANNER';
export const CLEAR_STORE_BANNER = 'CLEAR_STORE_BANNER';



export const AREAS = 'AREAS';
export const LOAD_DATA_AREAS_REQUEST = 'LOAD_DATA_AREAS_REQUEST';
export const LOAD_DATA_AREAS_SUCCESS = 'LOAD_DATA_AREAS_SUCCESS';
export const LOAD_DATA_AREAS_FAIL = 'LOAD_DATA_AREAS_FAIL';
export const LOAD_DATA_AREA_REQUEST = 'LOAD_DATA_AREA_REQUEST';
export const LOAD_DATA_AREA_SUCCESS = 'LOAD_DATA_AREA_SUCCESS';
export const UPDATE_AREA_REQUEST = 'UPDATE_AREA_REQUEST';
export const UPDATE_AREA_SUCCESS = 'UPDATE_AREA_SUCCESS';
export const UPDATE_AREA_FAIL = 'UPDATE_AREA_FAIL';
export const DELETE_AREA_REQUEST = 'DELETE_AREA_REQUEST';
export const DELETE_AREA_SUCCESS = 'DELETE_AREA_SUCCESS';
export const ADD_AREA_REQUEST = 'ADD_AREA_REQUEST';
export const ADD_AREA_SUCCESS = 'ADD_AREA_SUCCESS';
export const ADD_AREA_FAIL = 'ADD_AREA_FAIL';
export const SUGGESTIONS_FETCH_AREA = 'SUGGESTIONS_FETCH_AREA';
export const GET_WAREHOUSE_AREAS = 'GET_WAREHOUSE_AREAS';

export const COUNTRYS = 'COUNTRYS';
export const LOAD_DATA_COUNTRYS_REQUEST = 'LOAD_DATA_COUNTRYS_REQUEST';
export const LOAD_DATA_COUNTRYS_SUCCESS = 'LOAD_DATA_COUNTRYS_SUCCESS';
export const LOAD_DATA_COUNTRYS_FAIL = 'LOAD_DATA_COUNTRYS_FAIL';
export const LOAD_DATA_COUNTRY_REQUEST = 'LOAD_DATA_COUNTRY_REQUEST';
export const LOAD_DATA_COUNTRY_SUCCESS = 'LOAD_DATA_COUNTRY_SUCCESS';
export const UPDATE_COUNTRY_REQUEST = 'UPDATE_COUNTRY_REQUEST';
export const UPDATE_COUNTRY_SUCCESS = 'UPDATE_COUNTRY_SUCCESS';
export const UPDATE_COUNTRY_FAIL = 'UPDATE_COUNTRY_FAIL';
export const DELETE_COUNTRY_REQUEST = 'DELETE_COUNTRY_REQUEST';
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS';
export const ADD_COUNTRY_REQUEST = 'ADD_COUNTRY_REQUEST';
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS';
export const ADD_COUNTRY_FAIL = 'ADD_COUNTRY_FAIL';
export const SUGGESTIONS_FETCH_COUNTRY = 'SUGGESTIONS_FETCH_COUNTRY';
export const GET_WAREHOUSE_COUNTRYS = 'GET_WAREHOUSE_COUNTRYS';

export const CLEAR = 'CLEAR';

export const USERS = 'USERS';
export const LOAD_DATA_USERS_REQUEST = 'LOAD_DATA_USERS_REQUEST';
export const LOAD_DATA_USERS_SUCCESS = 'LOAD_DATA_USERS_SUCCESS';
export const LOAD_DATA_USERS_FAIL = 'LOAD_DATA_USERS_FAIL';
export const LOAD_DATA_USER_REQUEST = 'LOAD_DATA_USER_REQUEST';
export const LOAD_DATA_USER_SUCCESS = 'LOAD_DATA_USER_SUCCESS';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';
export const SUGGESTIONS_FETCH_USER = 'SUGGESTIONS_FETCH_USER';
export const GET_WAREHOUSE_USERS = 'GET_WAREHOUSE_USERS';
export const URL_CROP_IMG_USER = 'URL_CROP_IMG_USER';
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS';
export const GET_JOINING_SUCCESS = 'GET_JOINING_SUCCESS';
export const UPDATE_STATUS_USER_REQUEST = 'UPDATE_STATUS_USER_REQUEST';
export const UPDATE_STATUS_USER_SUCCESS = 'UPDATE_STATUS_USER_SUCCESS';
export const UPDATE_STATUS_USER_FAIL = 'UPDATE_STATUS_USER_FAIL';
export const LOAD_USER_TICKET_REQUEST = 'LOAD_USER_TICKET_REQUEST';
export const LOAD_USER_TICKET_SUCCESS = 'LOAD_USER_TICKET_SUCCESS';
export const LOAD_USER_TICKET_FAIL = 'LOAD_USER_TICKET_FAIL';

export const MANAGES = 'MANAGES';
export const LOAD_DATA_MANAGES_REQUEST = 'LOAD_DATA_MANAGES_REQUEST';
export const LOAD_DATA_MANAGES_SUCCESS = 'LOAD_DATA_MANAGES_SUCCESS';
export const LOAD_DATA_MANAGES_FAIL = 'LOAD_DATA_MANAGES_FAIL';
export const LOAD_DATA_MANAGE_REQUEST = 'LOAD_DATA_MANAGE_REQUEST';
export const LOAD_DATA_MANAGE_SUCCESS = 'LOAD_DATA_MANAGE_SUCCESS';
export const UPDATE_MANAGE_REQUEST = 'UPDATE_MANAGE_REQUEST';
export const UPDATE_MANAGE_SUCCESS = 'UPDATE_MANAGE_SUCCESS';
export const UPDATE_MANAGE_FAIL = 'UPDATE_MANAGE_FAIL';
export const DELETE_MANAGE_REQUEST = 'DELETE_MANAGE_REQUEST';
export const DELETE_MANAGE_SUCCESS = 'DELETE_MANAGE_SUCCESS';
export const ADD_MANAGE_REQUEST = 'ADD_MANAGE_REQUEST';
export const ADD_MANAGE_SUCCESS = 'ADD_MANAGE_SUCCESS';
export const ADD_MANAGE_FAIL = 'ADD_MANAGE_FAIL';
export const SUGGESTIONS_FETCH_MANAGE = 'SUGGESTIONS_FETCH_MANAGE';
export const GET_WAREHOUSE_MANAGES = 'GET_WAREHOUSE_MANAGES';
export const URL_CROP_IMG_MANAGE = 'URL_CROP_IMG_MANAGE';
export const UPDATE_STATUS_MANAGE_REQUEST = 'UPDATE_STATUS_MANAGE_REQUEST';
export const UPDATE_STATUS_MANAGE_SUCCESS = 'UPDATE_STATUS_MANAGE_SUCCESS';
export const UPDATE_STATUS_MANAGE_FAIL = 'UPDATE_STATUS_MANAGE_FAIL';
export const LOAD_MANAGE_TICKET_REQUEST = 'LOAD_MANAGE_TICKET_REQUEST';
export const LOAD_MANAGE_TICKET_SUCCESS = 'LOAD_MANAGE_TICKET_SUCCESS';
export const LOAD_MANAGE_TICKET_FAIL = 'LOAD_MANAGE_TICKET_FAIL';
export const DELETE_MANAGE_FAIL = 'DELETE_MANAGE_FAIL';
export const LOAD_DATA_MANAGE_NEWS_FAIL = 'LOAD_DATA_MANAGE_NEWS_FAIL';
export const LOAD_DATA_MANAGE_NEWS_REQUEST = 'LOAD_DATA_MANAGE_NEWS_REQUEST';
export const LOAD_DATA_MANAGE_NEWS_SUCCESS = 'LOAD_DATA_MANAGE_NEWS_SUCCESS';

//Dashboard
export const LOAD_DASHBOARD_REQUEST = 'LOAD_DASHBOARD_REQUEST';
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const LOAD_DASHBOARD_FAIL = 'LOAD_DASHBOARD_FAIL';

export const LOAD_DASHBOARD_CHART_EVENTS_REQUEST = 'LOAD_DASHBOARD_CHART_EVENTS_REQUEST';
export const LOAD_DASHBOARD_CHART_EVENTS_SUCCESS = 'LOAD_DASHBOARD_CHART_EVENTS_SUCCESS';
export const LOAD_DASHBOARD_CHART_EVENTS_FAIL = 'LOAD_DASHBOARD_CHART_EVENTS_FAIL';

export const LOAD_DATA_REPORTS_REQUEST = 'LOAD_DATA_REPORT_REQUEST';
export const LOAD_DATA_REPORTS_SUCCESS = 'LOAD_DATA_REPORT_SUCCESS';
export const LOAD_DATA_REPORTS_FAIL = 'LOAD_DATA_REPORT__FAIL';

export const LOAD_DATA_TICKETS_REQUEST = 'LOAD_DATA_TICKETS_REQUEST';
export const LOAD_DATA_TICKETS_SUCCESS = 'LOAD_DATA_TICKETS_SUCCESS';
export const LOAD_DATA_TICKETS_FAIL = 'LOAD_DATA_TICKETS__FAIL';

// TN SHOP
export const LOAD_DATA_CATEGORIES_REQUEST = 'LOAD_DATA_CATEGORIES_REQUEST';
export const LOAD_DATA_CATEGORIES_SUCCESS = 'LOAD_DATA_CATEGORIES_SUCCESS';
export const LOAD_DATA_CATEGORIES_FAIL = 'LOAD_DATA_CATEGORIES_FAIL';
export const LOAD_DATA_CATEGORIE_REQUEST = 'LOAD_DATA_CATEGORIE_REQUEST';
export const LOAD_DATA_CATEGORIE_SUCCESS = 'LOAD_DATA_CATEGORIE_SUCCESS';
export const LOAD_DATA_CATEGORIE_FAIL = 'LOAD_DATA_CATEGORIE_FAIL';
export const UPDATE_CATEGORIE_REQUEST = 'UPDATE_CATEGORIE_REQUEST';
export const UPDATE_CATEGORIE_SUCCESS = 'UPDATE_CATEGORIE_SUCCESS';
export const UPDATE_CATEGORIE_FAIL = 'UPDATE_CATEGORIE_FAIL';
export const DELETE_CATEGORIE_REQUEST = 'DELETE_CATEGORIE_REQUEST';
export const DELETE_CATEGORIE_SUCCESS = 'DELETE_CATEGORIE_SUCCESS';
export const DELETE_CATEGORIE_FAIL = 'DELETE_CATEGORIE_FAIL';
export const CLAER_CATEGORIES_STORE = 'CLAER_CATEGORIES_STORE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
export const LOAD_DATA_COMMENTS_REQUEST = 'LOAD_DATA_COMMENTS_REQUEST';
export const LOAD_DATA_COMMENTS_SUCCESS = 'LOAD_DATA_COMMENTS_SUCCESS';
export const LOAD_DATA_COMMENTS_FAIL = 'LOAD_DATA_COMMENTS_FAIL';
export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';
export const REP_COMMENT_REQUEST = 'REP_COMMENT_REQUEST';
export const REP_COMMENT_SUCCESS = 'REP_COMMENT_SUCCESS';
export const REP_COMMENT_FAIL = 'REP_COMMENT_FAIL';

export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';
export const LOAD_DATA_ORDERS_REQUEST = 'LOAD_DATA_ORDERS_REQUEST';
export const LOAD_DATA_ORDERS_SUCCESS = 'LOAD_DATA_ORDERS_SUCCESS';
export const LOAD_DATA_ORDERS_FAIL = 'LOAD_DATA_ORDERS_FAIL';
export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';


export const LOAD_DATA_PRODUCTS_REQUEST = 'LOAD_DATA_PRODUCTS_REQUEST';
export const LOAD_DATA_PRODUCTS_SUCCESS = 'LOAD_DATA_PRODUCTS_SUCCESS';
export const LOAD_DATA_PRODUCTS_FAIL = 'LOAD_DATA_PRODUCTS_FAIL';
export const LOAD_DATA_PRODUCT_REQUEST = 'LOAD_DATA_PRODUCT_REQUEST';
export const LOAD_DATA_PRODUCT_SUCCESS = 'LOAD_DATA_PRODUCT_SUCCESS';
export const LOAD_DATA_PRODUCT_FAIL = 'LOAD_DATA_PRODUCT_FAIL';
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const CLAER_PRODUCTS_STORE = 'CLAER_PRODUCTS_STORE';












